name: Gofmt on Push

on:
  push:
    branches:
      - main  # Adjust to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Run gofmt
      run: gofmt -w .

    # Define the name of the run
    run_name: Run Gofmt

