name: Golang Linter

run-name: Run Golangcli-lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    lint:
        name: Run Golang Linter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22

            - name: Install golangci-lint
              run: |
                  curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1
              if: success()

            - name: Run golangci-lint
              run: |
                  echo "Running golangci-lint..."
                  lint_result=$(golangci-lint run ./...)
                  echo "$lint_result"
